CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(60) NOT NULL,
  phone_number VARCHAR(255) NOT NULL
);

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  time_stamp timestamptz NOT NULL,
  delivery_time INTEGER NOT NULL,
  status VARCHAR(32) NOT NULL
)

CREATE TABLE carts (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  items_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL
)

CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  description INTEGER NOT NULL,
  -- image NOT NULL
  name VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL
)

CREATE TABLE restaurants (
  id SERIAL PRIMARY KEY NOT NULL,
  items_id INTEGER NOT NULL REFERENCES items (id) ON DELETE CASCADE,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(60) NOT NULL,
  location VARCHAR(255) NOT NULL,
  phone_number INTEGER NOT NULL
)